# .github/workflows/release.yml

name: Release Binary Executable

on:
  release:
    types: [created]


permissions:
  contents: write

jobs:
  build-release:
    name: Build and Release Executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and upload release binary
        uses: rust-build/rust-build.action@v1.4.5
        with:
          TOOLCHAIN_VERSION: stable
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_NAME: rdma-dashboard-rust-x86_64-linux
          ARCHIVE_TYPES: ""
          MINIFY: true
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
